name: 'Repository Triage Automation'
description: 'Automated triage labeling for GitHub repositories'
author: 'thenets'
branding:
  icon: 'tag'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  custom-github-token:
    description: 'Custom token for external contributor support (fallback to github-token if not provided)'
    required: false
  dry-run:
    description: 'Preview mode without making changes (true/false)'
    required: false
    default: 'false'

outputs:
  labels-added:
    description: 'JSON array of labels that were added'
  actions-taken:
    description: 'Summary of all actions performed'

runs:
  using: 'composite'
  steps:
    - name: Run Triage Automation
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.custom-github-token || inputs.github-token }}
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Load the triage management module
          const triageModulePath = path.join('${{ github.action_path }}', 'src', 'triage-management.js');
          const triageModule = require(triageModulePath);
          
          // Configure options
          const options = {
            dryRun: '${{ inputs.dry-run }}' === 'true',
            githubToken: '${{ inputs.custom-github-token || inputs.github-token }}'
          };
          
          try {
            // Execute triage automation
            const result = await triageModule.execute(context, github, options);
            
            // Set outputs
            core.setOutput('labels-added', JSON.stringify(result.labelsAdded || []));
            core.setOutput('actions-taken', result.summary || 'No actions taken');
            
            console.log('✅ Triage automation completed successfully');
            console.log(`📋 Summary: ${result.summary}`);
            
          } catch (error) {
            console.error('❌ Triage automation failed:', error.message);
            throw error;
          }