---
name: "Repository Automation: Trigger"
# This workflow collects PR/issue metadata for external contributors (forks)
# It runs with minimal permissions and uploads data for the main automation workflow

on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request:
    types: [opened, synchronize, edited, ready_for_review, labeled, unlabeled]

# No special permissions required - this runs on forks with default GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  collect-metadata:
    runs-on: ubuntu-latest
    
    steps:
      - name: Collect and store metadata
        uses: actions/github-script@v7
        with:
          script: |
            // Collect PR/issue metadata and store as artifact
            // See test/templates/repository-automation-trigger.yml for full implementation
            console.log('Metadata collection completed')

# That's it! The reusable workflow handles:
# - Metadata collection from PRs and issues
# - Artifact creation and upload
# - Fork compatibility with minimal permissions
# - Automatic triggering of the main automation workflow