---
# GitHub Repository Automations - Keeper: auto-add triage label
# MIT License - Copyright (c) 2025 Luiz Felipe F M Costa
# Source: https://github.com/thenets/repo-automations
#
# PERMISSIONS REQUIRED FOR FINE-GRAINED PERSONAL ACCESS TOKEN:
# When using a custom token (CUSTOM_GITHUB_TOKEN secret), the token must have:
# - Repository access: This repository (or "All repositories" for organization-wide use)
# - Repository permissions:
#   - Issues: Write (to add labels to issues)
#   - Pull requests: Write (to add labels to pull requests)
#   - Metadata: Read (to access repository information)
#
# SETUP INSTRUCTIONS:
# 1. Create a fine-grained personal access token at: https://github.com/settings/tokens?type=beta
# 2. Grant the permissions listed above
# 3. Add the token as a repository secret named 'CUSTOM_GITHUB_TOKEN'
# 4. This enables the workflow to run successfully for external contributors
#
# NOTE: Without a custom token, the workflow may fail for external contributors
# due to GitHub's default token permission restrictions.

name: "Keeper: auto-add triage label"

'on':
  issues:
    types: [opened]
  workflow_run:
    workflows: ["Keeper: fork trigger"]
    types: [completed]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-triage-label:
    runs-on: ubuntu-latest

    # CHANGE THIS: set your repo name here
    # this is used to prevent the workflow from running on other repos/forks
    if: github.repository == 'thenets/repo-automations'

    steps:
      - name: Add triage label to issue
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN || github.token }}
          script: |
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['triage']
              });
              console.log('✅ Successfully added triage label to issue #' +
                context.issue.number);
            } catch (error) {
              if (error.status === 403) {
                const errorMsg = `❌ Permission denied: Unable to add 'triage' label to issue #${context.issue.number}. This typically happens when the workflow is triggered by an external contributor and the repository doesn't have a CUSTOM_GITHUB_TOKEN secret configured with appropriate permissions. Repository administrators should add a CUSTOM_GITHUB_TOKEN secret with 'Issues: Write' permission.`;
                console.error(errorMsg);
                console.error('Error details:', error);
                throw new Error(errorMsg);
              } else if (error.status === 422) {
                // 422 could mean label already exists or label doesn't exist in repo
                // We need to check which case it is
                try {
                  const { data: existingLabels } = await github.rest.issues.listLabelsOnIssue({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number
                  });

                  const hasTriageLabel = existingLabels.some(label => label.name === 'triage');
                  if (hasTriageLabel) {
                    console.log('ℹ️ Triage label already exists on issue #' +
                      context.issue.number + ' - this is expected behavior');
                  } else {
                    // Label doesn't exist on issue, so 422 means label doesn't exist in repo
                    const errorMsg = `❌ Failed to add 'triage' label to issue #${context.issue.number}: Label 'triage' does not exist in the repository. Please create the 'triage' label in the repository settings.`;
                    console.error(errorMsg);
                    console.error('Error details:', error);
                    throw new Error(errorMsg);
                  }
                } catch (listError) {
                  const errorMsg = `❌ Error checking existing labels on issue #${context.issue.number}: ${listError.message}`;
                  console.error(errorMsg);
                  console.error('Error details:', listError);
                  throw new Error(errorMsg);
                }
              } else {
                const errorMsg = `❌ Unexpected error adding triage label to issue #${context.issue.number}: ${error.message}`;
                console.error(errorMsg);
                console.error('Error details:', error);
                throw new Error(errorMsg);
              }
            }

      - name: Add triage label to pull request
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN || github.token }}
          script: |
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['triage']
              });
              console.log('✅ Successfully added triage label to PR #' +
                context.issue.number);
            } catch (error) {
              if (error.status === 403) {
                const errorMsg = `❌ Permission denied: Unable to add 'triage' label to PR #${context.issue.number}. This typically happens when the workflow is triggered by an external contributor and the repository doesn't have a CUSTOM_GITHUB_TOKEN secret configured with appropriate permissions. Repository administrators should add a CUSTOM_GITHUB_TOKEN secret with 'Pull requests: Write' permission.`;
                console.error(errorMsg);
                console.error('Error details:', error);
                throw new Error(errorMsg);
              } else if (error.status === 422) {
                // 422 could mean label already exists or label doesn't exist in repo
                // We need to check which case it is
                try {
                  const { data: existingLabels } = await github.rest.issues.listLabelsOnIssue({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number
                  });

                  const hasTriageLabel = existingLabels.some(label => label.name === 'triage');
                  if (hasTriageLabel) {
                    console.log('ℹ️ Triage label already exists on PR #' +
                      context.issue.number + ' - this is expected behavior');
                  } else {
                    // Label doesn't exist on PR, so 422 means label doesn't exist in repo
                    const errorMsg = `❌ Failed to add 'triage' label to PR #${context.issue.number}: Label 'triage' does not exist in the repository. Please create the 'triage' label in the repository settings.`;
                    console.error(errorMsg);
                    console.error('Error details:', error);
                    throw new Error(errorMsg);
                  }
                } catch (listError) {
                  const errorMsg = `❌ Error checking existing labels on PR #${context.issue.number}: ${listError.message}`;
                  console.error(errorMsg);
                  console.error('Error details:', listError);
                  throw new Error(errorMsg);
                }
              } else {
                const errorMsg = `❌ Unexpected error adding triage label to PR #${context.issue.number}: ${error.message}`;
                console.error(errorMsg);
                console.error('Error details:', error);
                throw new Error(errorMsg);
              }
            }
