---
name: Keeper: auto-add triage label

'on':
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-triage-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add triage label to issue
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['triage']
              });
              console.log('Successfully added triage label to issue #' +
                context.issue.number);
            } catch (error) {
              if (error.status === 422) {
                console.log('Triage label already exists on issue #' +
                  context.issue.number);
              } else {
                console.error('Error adding triage label to issue:', error);
              }
            }

      - name: Add triage label to pull request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['triage']
              });
              console.log('Successfully added triage label to PR #' +
                context.issue.number);
            } catch (error) {
              if (error.status === 422) {
                console.log('Triage label already exists on PR #' +
                  context.issue.number);
              } else {
                console.error('Error adding triage label to PR:', error);
              }
            }
