---
# GitHub Repository Automations - Keeper: ready for review labeling
# MIT License - Copyright (c) 2025 Luiz Felipe F M Costa
# Source: https://github.com/thenets/repo-automations
#
# PERMISSIONS REQUIRED FOR FINE-GRAINED PERSONAL ACCESS TOKEN:
# When using a custom token (CUSTOM_GITHUB_TOKEN secret), the token must have:
# - Repository access: This repository (or "All repositories" for organization-wide use)
# - Repository permissions:
#   - Pull requests: Write (to add labels to pull requests)
#   - Metadata: Read (to access repository information)
#
# SETUP INSTRUCTIONS:
# 1. Create a fine-grained personal access token at: https://github.com/settings/tokens?type=beta
# 2. Grant the permissions listed above
# 3. Add the token as a repository secret named 'CUSTOM_GITHUB_TOKEN'
# 4. This enables the workflow to run successfully for external contributors
#
# NOTE: Without a custom token, the workflow may fail for external contributors
# due to GitHub's default token permission restrictions.

name: "Keeper: ready for review labeling"

'on':
  workflow_run:
    workflows: ["Keeper: fork trigger"]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  ready-for-review-labeling:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download event metadata
        uses: actions/download-artifact@v4
        with:
          name: event-metadata
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Add ready for review label to eligible PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN || github.token }}
          script: |
            // Load event metadata from artifact
            const fs = require('fs');
            const eventData = JSON.parse(fs.readFileSync('event-metadata.json', 'utf8'));
            console.log(`Processing ${eventData.event_type} #${eventData.issue_number} from workflow_run trigger`);

            // Only process pull request events
            if (eventData.event_type !== 'pull_request') {
              console.log(`Event type ${eventData.event_type} is not a pull request, skipping`);
              return;
            }

            try {
              // Get all labels on the pull request
              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: eventData.issue_number
              });

              const labelNames = labels.map(label => label.name);
              console.log(`Current labels on PR #${eventData.issue_number}: ${labelNames.join(', ')}`);

              // Check if PR has a release label and doesn't have triage label
              const hasReleaseLabel = labels.some(label => label.name.startsWith('release '));
              const hasTriageLabel = labels.some(label => label.name === 'triage');
              const hasReadyForReviewLabel = labels.some(label => label.name === 'ready for review');

              console.log(`Has release label: ${hasReleaseLabel}`);
              console.log(`Has triage label: ${hasTriageLabel}`);
              console.log(`Has ready for review label: ${hasReadyForReviewLabel}`);

              // Add "ready for review" label if conditions are met
              if (hasReleaseLabel && !hasTriageLabel && !hasReadyForReviewLabel) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: eventData.issue_number,
                  labels: ['ready for review']
                });
                console.log(`✅ Successfully added "ready for review" label to PR #${eventData.issue_number} (has release label, no triage label)`);
              } else if (hasReadyForReviewLabel) {
                console.log(`ℹ️ PR #${eventData.issue_number} already has "ready for review" label, skipping`);
              } else if (!hasReleaseLabel) {
                console.log(`ℹ️ PR #${eventData.issue_number} does not have a release label, skipping ready for review labeling`);
              } else if (hasTriageLabel) {
                console.log(`ℹ️ PR #${eventData.issue_number} still has triage label, not ready for review yet`);
              }

            } catch (error) {
              if (error.status === 403) {
                const errorMsg = `❌ Permission denied: Unable to add 'ready for review' label to PR #${eventData.issue_number}. This typically happens when the workflow is triggered by an external contributor and the repository doesn't have a CUSTOM_GITHUB_TOKEN secret configured with appropriate permissions. Repository administrators should add a CUSTOM_GITHUB_TOKEN secret with 'Pull requests: Write' permission.`;
                console.error(errorMsg);
                console.error('Error details:', error);
                throw new Error(errorMsg);
              } else if (error.status === 422) {
                // 422 could mean label already exists or label doesn't exist in repo
                // We need to check which case it is
                try {
                  const { data: existingLabels } = await github.rest.issues.listLabelsOnIssue({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: eventData.issue_number
                  });

                  const hasReadyForReviewLabel = existingLabels.some(label => label.name === 'ready for review');
                  if (hasReadyForReviewLabel) {
                    console.log(`ℹ️ "ready for review" label already exists on PR #${eventData.issue_number} - this is expected behavior`);
                  } else {
                    // Label doesn't exist on PR, so 422 means label doesn't exist in repo
                    const errorMsg = `❌ Failed to add 'ready for review' label to PR #${eventData.issue_number}: Label 'ready for review' does not exist in the repository. Please create the 'ready for review' label in the repository settings.`;
                    console.error(errorMsg);
                    console.error('Error details:', error);
                    throw new Error(errorMsg);
                  }
                } catch (listError) {
                  const errorMsg = `❌ Error checking existing labels on PR #${eventData.issue_number}: ${listError.message}`;
                  console.error(errorMsg);
                  console.error('Error details:', listError);
                  throw new Error(errorMsg);
                }
              } else {
                const errorMsg = `❌ Unexpected error adding ready for review label to PR #${eventData.issue_number}: ${error.message}`;
                console.error(errorMsg);
                console.error('Error details:', error);
                throw new Error(errorMsg);
              }
            }
